name: Build and run tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
    - name: checkout
      uses: actions/checkout@main

    - name: dir
      run: mkdir -p tools

    - name: mplc
      shell: bash
      run: |
        if [[ "${{ matrix.os }}" == 'windows-latest' ]]; then
          curl -LSs -o tools/mplc.exe https://github.com/Matway/mpl-c/releases/latest/download/mplc.exe;
        elif [[ "${{ matrix.os }}" == 'macos-latest' ]]; then
          curl -LSfs -o tools/mplc.ll https://github.com/Matway/mpl-c/releases/latest/download/mplc.ll && clang -O3 tools/mplc.ll -o tools/mplc;
        else
          curl -LSfs -o tools/mplc https://github.com/Matway/mpl-c/releases/latest/download/mplc && chmod +x tools/mplc;
        fi

    - name: test
      shell: bash
      run: if [[ "${{ matrix.os }}" == 'windows-latest' ]]; then ./test.bat tools/mplc; else sh test0.sh ./tools/mplc; fi

    - name: artifacts
      uses: actions/upload-artifact@main
      with:
        name: tests-${{ matrix.os }}
        path: |
          out/
          tools/mplc
          tools/mplc.exe
